config/routes.rb
Cirqueperformers::Application.routes.draw do
  resources :performers
  root :to => 'performers#index'

end

app/models/performer.rb
class Performer < ActiveRecord::Base
  attr_accessible :act, :description, :email, :name, :nationality, :passport, :phone, :rate, :website
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  # GET /performers
  # GET /performers.json
  def index
    @performers = Performer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @performers }
    end
  end

  # GET /performers/1
  # GET /performers/1.json
  def show
    @performer = Performer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @performer }
    end
  end

  # GET /performers/new
  # GET /performers/new.json
  def new
    @performer = Performer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @performer }
    end
  end

  # GET /performers/1/edit
  def edit
    @performer = Performer.find(params[:id])
  end

  # POST /performers
  # POST /performers.json
  def create
    @performer = Performer.new(params[:performer])

    respond_to do |format|
      if @performer.save
        format.html { redirect_to @performer, notice: 'Performer was successfully created.' }
        format.json { render json: @performer, status: :created, location: @performer }
      else
        format.html { render action: "new" }
        format.json { render json: @performer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /performers/1
  # PUT /performers/1.json
  def update
    @performer = Performer.find(params[:id])

    respond_to do |format|
      if @performer.update_attributes(params[:performer])
        format.html { redirect_to @performer, notice: 'Performer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @performer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performers/1
  # DELETE /performers/1.json
  def destroy
    @performer = Performer.find(params[:id])
    @performer.destroy

    respond_to do |format|
      format.html { redirect_to performers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/performers_helper.rb
module PerformersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cirqueperformers</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/performers/_form.html.erb
<%= form_for(@performer) do |f| %>
  <% if @performer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@performer.errors.count, "error") %> prohibited this performer from being saved:</h2>

      <ul>
      <% @performer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :act %><br />
    <%= f.text_field :act %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :nationality %><br />
    <%= f.text_field :nationality %>
  </div>
  <div class="field">
    <%= f.label :passport %><br />
    <%= f.number_field :passport %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/performers/edit.html.erb
<h1>Editing performer</h1>

<%= render 'form' %>

<%= link_to 'Show', @performer %> |
<%= link_to 'Back', performers_path %>

app/views/performers/index.html.erb
<h1>Listing performers</h1>

<table>
  <tr>
    <th>Act</th>
    <th>Name</th>
    <th>Rate</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Nationality</th>
    <th>Passport</th>
    <th>Website</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @performers.each do |performer| %>
  <tr>
    <td><%= performer.act %></td>
    <td><%= performer.name %></td>
    <td><%= performer.rate %></td>
    <td><%= performer.email %></td>
    <td><%= performer.phone %></td>
    <td><%= performer.nationality %></td>
    <td><%= performer.passport %></td>
    <td><%= performer.website %></td>
    <td><%= performer.description %></td>
    <td><%= link_to 'Show', performer %></td>
    <td><%= link_to 'Edit', edit_performer_path(performer) %></td>
    <td><%= link_to 'Destroy', performer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Performer', new_performer_path %>

app/views/performers/new.html.erb
<h1>New performer</h1>

<%= render 'form' %>

<%= link_to 'Back', performers_path %>

app/views/performers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Act:</b>
  <%= @performer.act %>
</p>

<p>
  <b>Name:</b>
  <%= @performer.name %>
</p>

<p>
  <b>Rate:</b>
  <%= @performer.rate %>
</p>

<p>
  <b>Email:</b>
  <%= @performer.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @performer.phone %>
</p>

<p>
  <b>Nationality:</b>
  <%= @performer.nationality %>
</p>

<p>
  <b>Passport:</b>
  <%= @performer.passport %>
</p>

<p>
  <b>Website:</b>
  <%= @performer.website %>
</p>

<p>
  <b>Description:</b>
  <%= @performer.description %>
</p>


<%= link_to 'Edit', edit_performer_path(@performer) %> |
<%= link_to 'Back', performers_path %>